### ISSUE TITLE
takeWith

### ISSUE THREAD

**Issue by fabienjuif** [alakarteio/k-simple-state#36]
### Context
this issue is about `takeWith` where currying is reversed from `take`
 - take: `take(filter)(reaction)`
 - takeWith: `takeWith(reaction)(filter)`

The approach is more convenient to write **OR**:
**take version**
```js
take(filter1, andFilter2)(reactionImpl)
take(orFilter3)(reactionImpl)
```

**takeWith version**
```js
const reaction = takeWith(reactionImpl)
// ...
takeWith(filter1, andFilter2)
takeWith(orFilter3)
```

### **So why this `takeWith` is not in the lib ?**
Good question! This is because this example shows that we are not familiar with this pattern, since we can't find a propre name to `complete` fonction:
```js
// todos.js
import { takeWith } from 'k-simple-state'
 
export const complete = takeWith(action, store) => {
  const { todos } = store.data 
  const todo = todos.get(action.payload)
  todos.set({ ...todos, completed: true })
}

// listeners.js
import { complete } from './todos' 

export default [
  // here it seems odd to me to call a fonction 'complete' passing an action type :)
  complete('@@ui/CLICKED_COMPLETE'),
]
```

### What's next ?
When someone will find a proper naming convention we will write the `takeWith` and publish it in this lib.
As long as we can't find that we don't publish it 🙂

### Source
#26 

cc @bpetetot @EmrysMyrddin @guillaumecrespel

**Comment by bpetetot** [comment]
It's remind me event-based actions : 
* `take` means `on(event)` handle actions
* `takeWith` means `handle(action)` on event

so it will be : 
```es6
 // take
 on(filters)(reaction)

 // takeWith
 handle(reaction)(filters)
```

And your example can be written like that : 
```es6
// todos.js
import { handle } from 'k-simple-state'
 
export const complete = handle(action, store) => {
  const { todos } = store.data 
  const todo = todos.get(action.payload)
  todos.set({ ...todos, completed: true })
}

// listeners.js
import { complete } from './todos' 

export default [
  // here it seems odd to me to call a fonction 'complete' passing an action type :)
  complete('@@ui/CLICKED_COMPLETE'),
]
```

And this is an common vocabulary for `listeners`

**Comment by bpetetot** [comment]
We can also use `when` instead of `on` : 
```es6
 // take
 when(filters)(reaction)

 // takeWith
 handle(reaction)(filters)
```

**Comment by EmrysMyrddin** [comment]
The issue here is more the name of the generated function, not the API.
Here `handleComplete` doesn' represent well the fact that it's a reaction waiting for filters. With this name, I expect a function that can handle the `Complete` action.

**Comment by bpetetot** [comment]
Ok, my bad...

So, your looking for something like that :
```es6
// todos.js
import { handle } from 'k-simple-state'
 
export const complete = takeWith((action, store) => {
  const { todos } = store.data 
  const todo = todos.get(action.payload)
  todos.set({ ...todos, completed: true })
})

// listeners.js
import { handleComplete } from './todos' 

export default [
  complete.on('@@ui/CLICKED_COMPLETE'),
]
```

**Comment by EmrysMyrddin** [comment]
Yes, perhaps it's a good way to explore.
For `complete.on`, I have the expectation to handle an envent on the `complete` object 😄 
Perhaps with another word ? `complete.if()` for example ?

**Comment by bpetetot** [comment]
```es6
complete.when('@@ui/CLICKED_COMPLETE')
```

**Comment by EmrysMyrddin** [comment]
```es6
complete.match('@@ui/CLICKED_COMPLETE')
```

**Comment by fabienjuif** [comment]
I prefer the `complete.when()` this is more fluent I think

**Comment by EmrysMyrddin** [comment]
At this time, `compleWhen` can be ok isn't it ?

**Comment by fabienjuif** [comment]
yes it can:
```js
// todos.js
import { takeWith } from 'k-simple-state'
 
export const completeWhen = takeWith(action, store) => {
  const { todos } = store.data 
  const todo = todos.get(action.payload)
  todos.set({ ...todos, completed: true })
}

// listeners.js
import { completeWhen } from './todos' 

export default [
  // here it seems odd to me to call a fonction 'complete' passing an action type :)
  completeWhen('@@ui/CLICKED_COMPLETE'),
]
```
?

**Comment by fabienjuif** [comment]
I am waiting for @bpetetot POV

**Comment by bpetetot** [comment]
I'm agree with the wording : `when`

But I'm not really convinced by the naming convention instead of a DSL.

A DSL could be more extensible :
```es6
  complete.when('@@ui/CLICKED_COMPLETE')
  complete.whenLatest('@@ui/CLICKED_COMPLETE')
  complete.whenDebounce('@@ui/CLICKED_COMPLETE', 500)
```
But it could be more complicated to implement.

**Comment by fabienjuif** [comment]
I don't think this more complicated to implement.
We can even write both API I think.
```js
complete('@@ui/CLICKED_COMPLETE') // or rename the function completeWhen
complete.when('@@ui/CLICKED_COMPLETE')
```

**Comment by EmrysMyrddin** [comment]
I'm not found of object notation DSLs... If you want to do this, I prefere
hight order function like `latest(takeWhike(...)(...))`. And it can be
applied to both take and takeWhile.

**Comment by fabienjuif** [comment]
@EmrysMyrddin the problem with this kind of approach is the number of different exports, and maybe collisions

Or maybe we can have:
```js
import { reaction } from 'k-simple-state'

const { latest, take /* or when */, etc } = reaction

// ...
```

**Comment by bpetetot** [comment]
So in summary, maybe something more like that  ? 
```es6
import { latest, take, takeWith } from 'k-simple-state/reactions'

// take version
const onComplete = latest(take('@@ui/CLICKED_COMPLETE'))
onComplete(() => /* do something */)

// takeWith version
const completeWhen = takeWith(() => /* do something */)
latest(completeWhen('@@ui/CLICKED_COMPLETE'))
```

is it easily understandable when you read the code ?

**Comment by fabienjuif** [comment]
this is more `completeWhen(latest('@@ui/CLICKED_COMPLETE'))` ?
Because when I read `latest(completeWhen('@@ui/CLICKED_COMPLETE'))` I understand this the latest reaction to happen and triggered.

What we want is the latest `action` not the reaction (this is to late)

**Comment by bpetetot** [comment]
Maybe more understandable with composition : 
```es6
// take version
compose(latest, take)('@@ui/CLICKED_COMPLETE')

// takeWith version
compose(completeWhen, latest)('@@ui/CLICKED_COMPLETE')
```

**Comment by fabienjuif** [comment]
If we use composition of fonctions maybe we have to rename APIs as you suggested before @bpetetot.
 - takeWith -> reaction
 - take -> when

```js
const complete = (action, store) => { /* do something */}

// debounce events and call `complete`
compose(
  when('@@ui/CLICKED_COMPLETE')
  debounce, 
)(complete)

// same thing different approach
const debouncedComplete = debounce(complete)
when('@@ui/CLICKED_COMPLETE')(debouncedComplete)
when('@@ui/OTHER_CLICKED')(debouncedComplete)

// calls `complete` on every events
when('@@ui/CLICKED_COMPLETE')(complete)
```
I think we agree **BUT** take care this is not the concern of this lib, you can find a `debounce` on lodash, a `log` in other lib, etc. I don't think this is our purpose.

The **main purpose of the lib** is to respond with ease to 90% of our developpement.
Which will be something like:
```js
when('@@ui/CLICKED_COMPLETE')(complete)
```

or:
```js
reaction(complete).when('@@ui/CLICKED_COMPLETE')
reaction(complete).when('@@ui/CLICKED_COMPLETE_2')
```

**Comment by fabienjuif** [comment]
We can then imagine that for all cases we have to decorate our reactions:
**todos.js**
```js
import { reaction } from 'k-simple-state'
 
export const complete = reaction(action, store) => {
  const { todos } = store.data 
  const todo = todos.get(action.payload)
  todos.set({ ...todos, completed: true })
}
```

**listeners.js**
```js
import { when } from 'k-simple-state'
import { complete } from './todos

export default [
  complete.when('@@ui/CLICKED_COMPLETE'),
  // or
  when('@@ui/CLICKED_COMPLETE')(complete),
]

**Comment by bpetetot** [comment]
Seems nice ! 👌 
And I'm agree that is not the purpose of the lib to bring `debounce`, it was just to illustrate my thoughts.
