### ISSUE TITLE
add greenkeeper

### ISSUE THREAD

**Issue by fabienjuif** [alakarteio/k-simple-state#46]
@bpetetot you already did this right ? 😅

**Comment by bpetetot** [comment]
It's really easy.
You just have to [activate greenkeeper on this repo](https://greenkeeper.io/docs.html#installation) and launch a build to the CI, then Greenkeeper will be activated automatically.

**Comment by fabienjuif** [comment]
#51

**Comment by fabienjuif** [comment]
#53 - initial PR

**Comment by fabienjuif** [comment]
I am waiting for a first PR (initial init excluded) to close this issue

**Comment by fabienjuif** [comment]
#62 proof that works
